{% set name = "sudachidict-small" %}
{% set version = "20241021" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SudachiDict-small-{{ version }}.tar.gz
  sha256: ea72297c2331c0fbbf471fbb6b136a70b3ba91ad39f4ccaea337c2b54eb7eb02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - sudachipy >=0.5,<0.7

test:
  imports:
    - sudachidict_small
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WorksApplications/SudachiDict
  summary: Sudachi Dictionary for SudachiPy - Small Edition
  license: Apache-2.0
  license_file:
    - LICENSE-2.0.txt
    - sudachidict_small/resources/LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - apmorton
