{% set name = "sudachidict-small" %}
{% set version = "20250515" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4051882955484ec8851329c736732d17de89f2d38c3c88fbbe6d2f7544e052fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sudachipy >=0.5,<0.7

test:
  imports:
    - sudachidict_small
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WorksApplications/SudachiDict
  summary: Sudachi Dictionary for SudachiPy - Small Edition
  license: Apache-2.0
  license_file:
    - LICENSE-2.0.txt
    - sudachidict_small/resources/LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - apmorton
